owner: oneminch
repo: Status

sites:
  - name: Portfolio
    url: https://oneminch.dev
  - name: EncryptedList
    url: https://encryptedlist.xyz
  - name: PlayTales 
    url: https://playtales.oneminch.dev

status-website:
  baseUrl: /Status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  theme: dark
  introMessage: Uptime monitor for portfolio and projects
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
      
workflowSchedule:
  graphs: "0 9 * * 2"
  responseTime: "0 9 * * 2"
  staticSite: "0 9 * * 2"
  summary: "0 9 * * 2"
  updateTemplate: "0 23 * * *"
  updates: "0 23 * * *"
  uptime: "0 9 * * 2"
