owner: oneminch
repo: uptime-monitor

sites:
  - name: Portfolio
    url: https://oneminch.dev
  - name: EncryptedList
    url: https://encryptedlist.xyz
  - name: Oneminch Blob
    url: https://blog.oneminch.dev

status-website:
  baseUrl: /uptime-monitor
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Uptime monitor for portfolio and EncryptedList
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
      
